//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MallManager {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MainResourses {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainResourses() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MallManager.MainResourses", typeof(MainResourses).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некорректное значение языка в конфиге, по умолчанию будет использоваться русская локаль.
        /// </summary>
        internal static string ApplyLocalizationErrorMessageIncorrectLanguageNameInConfig {
            get {
                return ResourceManager.GetString("ApplyLocalizationErrorMessageIncorrectLanguageNameInConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не указано значение языка в конфиге, по умолчанию будет использоваться русская локаль.
        /// </summary>
        internal static string ApplyLocalizationErrorMessageNotFoundLanguageNameInConfig {
            get {
                return ResourceManager.GetString("ApplyLocalizationErrorMessageNotFoundLanguageNameInConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавление помещения.
        /// </summary>
        internal static string fmEditRoom_AddRoomCaption {
            get {
                return ResourceManager.GetString("fmEditRoom_AddRoomCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование помещения.
        /// </summary>
        internal static string fmEditRoom_EditRoomCaption {
            get {
                return ResourceManager.GetString("fmEditRoom_EditRoomCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить выбранное помещение?.
        /// </summary>
        internal static string fmMain_ShureDeleteRoomQuestion {
            get {
                return ResourceManager.GetString("fmMain_ShureDeleteRoomQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внимание.
        /// </summary>
        internal static string fmMain_WarningCaption {
            get {
                return ResourceManager.GetString("fmMain_WarningCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внутреннее сообщение об ошибке.
        /// </summary>
        internal static string InnerMessageAboutExeption {
            get {
                return ResourceManager.GetString("InnerMessageAboutExeption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Магазин.
        /// </summary>
        internal static string RoomTypeEnumShop {
            get {
                return ResourceManager.GetString("RoomTypeEnumShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПСЗ(Помещение Свободного Назначения).
        /// </summary>
        internal static string RoomTypeEnumSpace {
            get {
                return ResourceManager.GetString("RoomTypeEnumSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Киоск.
        /// </summary>
        internal static string RoomTypeEnumStand {
            get {
                return ResourceManager.GetString("RoomTypeEnumStand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Супермаркет.
        /// </summary>
        internal static string RoomTypeEnumSupermarket {
            get {
                return ResourceManager.GetString("RoomTypeEnumSupermarket", resourceCulture);
            }
        }
    }
}
